// Mock data for development without database

// Helper to get dates relative to today (must be defined before use)
const getDateString = (daysOffset: number) => {
  const date = new Date();
  date.setDate(date.getDate() + daysOffset);
  return date.toISOString().split('T')[0];
};

export const mockUsers = [
  {
    id: '1',
    email: 'admin@gmys.com',
    password: 'admin123',
    firstName: 'Admin',
    lastName: 'User',
    role: 'SYSTEM_ADMIN',
    vesselId: null,
    isActive: true,
  },
  {
    id: '2',
    email: 'dpa@gmys.com',
    password: 'dpa123',
    firstName: 'DPA',
    lastName: 'Manager',
    role: 'DPA_OFFICE',
    vesselId: null,
    isActive: true,
  },
  {
    id: '3',
    email: 'captain@gmys.com',
    password: 'captain123',
    firstName: 'John',
    lastName: 'Captain',
    role: 'CAPTAIN',
    vesselId: '1',
    isActive: true,
  },
];

export const mockVessels = [
  {
    id: '1',
    name: 'MV Blue Ocean',
    imoNumber: 'IMO1234567',
    vesselType: 'TANKER',
    flag: 'Turkey',
    location: 'Mediterranean Sea',
    latitude: 36.8969,
    longitude: 30.7133,
    documents: [],
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    name: 'MV Sea Star',
    imoNumber: 'IMO2345678',
    vesselType: 'BULKER',
    flag: 'Turkey',
    location: 'Black Sea',
    latitude: 41.0082,
    longitude: 28.9784,
    documents: [],
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2024-01-20T10:00:00Z',
  },
  {
    id: '3',
    name: 'MV Cargo Express',
    imoNumber: 'IMO3456789',
    vesselType: 'CONTAINER',
    flag: 'Turkey',
    location: 'Aegean Sea',
    latitude: 38.4237,
    longitude: 27.1428,
    documents: [],
    createdAt: '2024-02-01T10:00:00Z',
    updatedAt: '2024-02-01T10:00:00Z',
  },
];

export const mockCategories = [
  {
    id: '1',
    name: 'Sertifikalar',
    description: 'Gemi sertifikaları',
    type: 'CERTIFICATE',
    isActive: true,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: '2',
    name: 'Teknik Çizimler',
    description: 'Teknik çizimler ve planlar',
    type: 'TECHNICAL_DRAWING',
    isActive: true,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: '3',
    name: 'HSEQ',
    description: 'Sağlık, güvenlik, çevre ve kalite',
    type: 'HSEQ',
    isActive: true,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: '4',
    name: 'Jurnaller',
    description: 'Gemi jurnalleri',
    type: 'JOURNAL',
    isActive: true,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
];

export const mockDocuments = [
  {
    id: '1',
    title: 'International Tonnage Certificate',
    description: 'Uluslararası tonaj sertifikası',
    filePath: '/documents/cert-1.pdf',
    fileName: 'tonnage-certificate.pdf',
    fileSize: 245760,
    mimeType: 'application/pdf',
    fileHash: 'abc123',
    version: 1,
    status: 'APPROVED',
    isActive: true,
    vesselId: '1',
    categoryId: '1',
    uploadedById: '3',
    vessel: mockVessels[0],
    category: mockCategories[0],
    uploadedBy: mockUsers[2],
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: '2',
    title: 'Safety Management Certificate',
    description: 'Güvenlik yönetim sertifikası',
    filePath: '/documents/cert-2.pdf',
    fileName: 'safety-certificate.pdf',
    fileSize: 512000,
    mimeType: 'application/pdf',
    fileHash: 'def456',
    version: 1,
    status: 'APPROVED',
    isActive: true,
    vesselId: '1',
    categoryId: '1',
    uploadedById: '3',
    vessel: mockVessels[0],
    category: mockCategories[0],
    uploadedBy: mockUsers[2],
    createdAt: '2024-01-12T10:00:00Z',
    updatedAt: '2024-01-12T10:00:00Z',
  },
  {
    id: '3',
    title: 'Engine Room Layout',
    description: 'Makine dairesi yerleşim planı',
    filePath: '/documents/tech-1.pdf',
    fileName: 'engine-room-layout.pdf',
    fileSize: 1024000,
    mimeType: 'application/pdf',
    fileHash: 'ghi789',
    version: 2,
    status: 'PENDING_APPROVAL',
    isActive: true,
    vesselId: '1',
    categoryId: '2',
    uploadedById: '3',
    vessel: mockVessels[0],
    category: mockCategories[1],
    uploadedBy: mockUsers[2],
    createdAt: '2024-02-01T10:00:00Z',
    updatedAt: '2024-02-01T10:00:00Z',
  },
  {
    id: '4',
    title: 'Daily Engine Log',
    description: 'Günlük makine jurnali',
    filePath: '/documents/journal-1.pdf',
    fileName: 'daily-log-2024-02.pdf',
    fileSize: 128000,
    mimeType: 'application/pdf',
    fileHash: 'jkl012',
    version: 1,
    status: 'DRAFT',
    isActive: true,
    vesselId: '2',
    categoryId: '4',
    uploadedById: '3',
    vessel: mockVessels[1],
    category: mockCategories[3],
    uploadedBy: mockUsers[2],
    createdAt: '2024-02-15T10:00:00Z',
    updatedAt: '2024-02-15T10:00:00Z',
  },
  {
    id: '5',
    title: 'Pollution Prevention Certificate',
    description: 'Kirlilik önleme sertifikası',
    filePath: '/documents/cert-3.pdf',
    fileName: 'pollution-certificate.pdf',
    fileSize: 384000,
    mimeType: 'application/pdf',
    fileHash: 'mno345',
    version: 1,
    status: 'APPROVED',
    isActive: true,
    vesselId: '2',
    categoryId: '1',
    uploadedById: '3',
    vessel: mockVessels[1],
    category: mockCategories[0],
    uploadedBy: mockUsers[2],
    createdAt: '2024-01-05T10:00:00Z',
    updatedAt: '2024-01-05T10:00:00Z',
  },
];

export const mockLogbookEntries = [
  {
    id: '1',
    vesselId: '1',
    vessel: mockVessels[0],
    entryDate: new Date().toISOString().split('T')[0],
    entryTime: '08:00',
    latitude: 36.8969,
    longitude: 30.7133,
    weather: 'Clear',
    seaState: 'Calm',
    windDirection: 'NW',
    windSpeed: 10.5,
    visibility: 12.0,
    events: 'Normal navigation, no incidents',
    remarks: 'All systems operational',
    officerId: '3',
    officer: mockUsers[2],
    captainId: null,
    captain: null,
    isSigned: false,
    signedAt: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    vesselId: '1',
    vessel: mockVessels[0],
    entryDate: getDateString(-1),
    entryTime: '12:00',
    latitude: 37.0000,
    longitude: 31.0000,
    weather: 'Partly Cloudy',
    seaState: 'Moderate',
    windDirection: 'SW',
    windSpeed: 15.0,
    visibility: 10.0,
    events: 'Port call at Mersin, cargo loading completed',
    remarks: 'All operations completed successfully',
    officerId: '3',
    officer: mockUsers[2],
    captainId: '3',
    captain: mockUsers[2],
    isSigned: true,
    signedAt: getDateString(-1),
    createdAt: getDateString(-1),
    updatedAt: getDateString(-1),
  },
];

export const mockEngineLogs = [
  {
    id: '1',
    vesselId: '1',
    vessel: mockVessels[0],
    logDate: new Date().toISOString().split('T')[0],
    logTime: '08:00',
    engineHours: 1250.5,
    rpm: 750,
    fuelLevel: 85.5,
    oilPressure: 4.2,
    waterTemperature: 85,
    exhaustTemperature: 420,
    oilTemperature: 90,
    loadPercentage: 75,
    alarms: null,
    maintenanceNotes: 'Rutin kontrol yapıldı',
    remarks: 'Tüm parametreler normal',
    engineerId: '2',
    engineer: mockUsers[1],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockFuelConsumptions = [
  {
    id: '1',
    vesselId: '1',
    vessel: mockVessels[0],
    operationType: 'BUNKER',
    operationDate: getDateString(-5),
    quantity: 5000,
    unitPrice: 1.5,
    totalCost: 7500,
    tank: 'Main Tank',
    tankLevelBefore: 30,
    tankLevelAfter: 80,
    supplier: 'Marine Fuel Co.',
    port: 'Istanbul',
    qualityTest: 'Passed',
    remarks: 'Bunker operation completed',
    recordedById: '2',
    recordedBy: mockUsers[1],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    vesselId: '1',
    vessel: mockVessels[0],
    operationType: 'CONSUMPTION',
    operationDate: new Date().toISOString().split('T')[0],
    quantity: 150,
    unitPrice: null,
    totalCost: null,
    tank: 'Main Tank',
    tankLevelBefore: 80,
    tankLevelAfter: 77,
    supplier: null,
    port: null,
    qualityTest: null,
    remarks: 'Daily consumption',
    recordedById: '2',
    recordedBy: mockUsers[1],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockPSCChecklists = [
  {
    id: '1',
    vesselId: '1',
    vessel: mockVessels[0],
    inspectionDate: getDateString(-10),
    port: 'Istanbul',
    inspector: 'Port State Control Officer',
    overallStatus: 'COMPLIANT',
    checklistItems: [
      { category: 'Certificates', item: 'Safety Management Certificate', status: 'COMPLIANT' },
      { category: 'Certificates', item: 'International Tonnage Certificate', status: 'COMPLIANT' },
      { category: 'Safety Equipment', item: 'Lifeboats', status: 'COMPLIANT' },
      { category: 'Safety Equipment', item: 'Fire Extinguishers', status: 'COMPLIANT' },
      { category: 'Navigation', item: 'Radar', status: 'COMPLIANT' },
    ],
    deficiencies: null,
    remarks: 'All items checked and compliant',
    preparedById: '2',
    preparedBy: mockUsers[1],
    createdAt: getDateString(-10),
    updatedAt: getDateString(-10),
  },
  {
    id: '2',
    vesselId: '2',
    vessel: mockVessels[1],
    inspectionDate: getDateString(-5),
    port: 'Mersin',
    inspector: 'Port State Control Officer',
    overallStatus: 'PARTIAL',
    checklistItems: [
      { category: 'Certificates', item: 'Safety Management Certificate', status: 'COMPLIANT' },
      { category: 'Safety Equipment', item: 'Lifeboats', status: 'NON_COMPLIANT', notes: 'Lifeboat davit needs maintenance' },
      { category: 'Navigation', item: 'GPS', status: 'COMPLIANT' },
    ],
    deficiencies: 'Lifeboat davit maintenance required',
    remarks: 'Minor deficiency noted, corrective action plan submitted',
    preparedById: '2',
    preparedBy: mockUsers[1],
    createdAt: getDateString(-5),
    updatedAt: getDateString(-5),
  },
];

export const mockSafetyDrills = [
  {
    id: '1',
    vesselId: '1',
    vessel: mockVessels[0],
    drillType: 'FIRE',
    status: 'COMPLETED',
    plannedDate: getDateString(-7),
    actualDate: getDateString(-7),
    startTime: '10:00',
    endTime: '10:30',
    durationMinutes: 30,
    participants: 'All crew members',
    observations: 'Drill completed successfully, all crew responded promptly',
    improvements: 'Fire extinguisher locations should be more clearly marked',
    remarks: 'Monthly fire drill as per ISM requirements',
    conductedById: '3',
    conductedBy: mockUsers[2],
    createdAt: getDateString(-7),
    updatedAt: getDateString(-7),
  },
  {
    id: '2',
    vesselId: '1',
    vessel: mockVessels[0],
    drillType: 'ABANDON_SHIP',
    status: 'PLANNED',
    plannedDate: getDateString(7),
    actualDate: null,
    startTime: null,
    endTime: null,
    durationMinutes: null,
    participants: null,
    observations: null,
    improvements: null,
    remarks: 'Scheduled monthly abandon ship drill',
    conductedById: null,
    conductedBy: null,
    createdAt: getDateString(-14),
    updatedAt: getDateString(-14),
  },
];

export const mockCertificates = [
  {
    id: '1',
    docId: '1',
    issueDate: '2023-01-15',
    expiryDate: getDateString(365), // 1 yıl sonra (aktif)
    warningThreshold: 30,
    issuingAuthority: 'Turkish Maritime Authority',
    certificateNumber: 'CERT-2023-001',
    isNotified30: false,
    isNotified60: false,
    isNotified90: false,
    document: mockDocuments[0],
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: '2',
    docId: '2',
    issueDate: '2023-06-01',
    expiryDate: getDateString(20), // 20 gün sonra (yakında dolacak - warning)
    warningThreshold: 30,
    issuingAuthority: 'IMO',
    certificateNumber: 'CERT-2023-002',
    isNotified30: true,
    isNotified60: false,
    isNotified90: false,
    document: mockDocuments[1],
    createdAt: '2024-01-12T10:00:00Z',
    updatedAt: '2024-01-12T10:00:00Z',
  },
  {
    id: '3',
    docId: '5',
    issueDate: '2022-12-01',
    expiryDate: getDateString(-15), // 15 gün önce (süresi dolmuş)
    warningThreshold: 30,
    issuingAuthority: 'Flag State',
    certificateNumber: 'CERT-2022-003',
    isNotified30: true,
    isNotified60: true,
    isNotified90: true,
    document: mockDocuments[4],
    createdAt: '2024-01-05T10:00:00Z',
    updatedAt: '2024-01-05T10:00:00Z',
  },
  {
    id: '4',
    docId: '1',
    issueDate: '2023-03-01',
    expiryDate: getDateString(180), // 6 ay sonra (aktif)
    warningThreshold: 30,
    issuingAuthority: 'Classification Society',
    certificateNumber: 'CERT-2023-004',
    isNotified30: false,
    isNotified60: false,
    isNotified90: false,
    document: mockDocuments[0],
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2024-01-20T10:00:00Z',
  },
];

export const mockCrewMembers = [
  {
    id: '1',
    firstName: 'Ahmet',
    lastName: 'Yılmaz',
    middleName: null,
    seafarerId: 'SEA001',
    passportNumber: 'P123456',
    nationality: 'Turkey',
    dateOfBirth: '1985-05-15',
    phoneNumber: '+90 555 123 4567',
    email: 'ahmet.yilmaz@example.com',
    position: 'CAPTAIN',
    status: 'ACTIVE',
    joinDate: '2024-01-01',
    yearsOfExperience: 15,
    vesselId: '1',
    vessel: mockVessels[0],
    certificates: [],
    trainings: [],
    rotations: [],
    notes: null,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: '2',
    firstName: 'Mehmet',
    lastName: 'Demir',
    middleName: null,
    seafarerId: 'SEA002',
    passportNumber: 'P234567',
    nationality: 'Turkey',
    dateOfBirth: '1990-08-20',
    phoneNumber: '+90 555 234 5678',
    email: 'mehmet.demir@example.com',
    position: 'CHIEF_ENGINEER',
    status: 'ACTIVE',
    joinDate: '2024-01-05',
    yearsOfExperience: 10,
    vesselId: '1',
    vessel: mockVessels[0],
    certificates: [],
    trainings: [],
    rotations: [],
    notes: null,
    createdAt: '2024-01-05T10:00:00Z',
    updatedAt: '2024-01-05T10:00:00Z',
  },
  {
    id: '3',
    firstName: 'Ali',
    lastName: 'Kaya',
    middleName: null,
    seafarerId: 'SEA003',
    passportNumber: 'P345678',
    nationality: 'Turkey',
    dateOfBirth: '1992-03-10',
    phoneNumber: '+90 555 345 6789',
    email: 'ali.kaya@example.com',
    position: 'CHIEF_OFFICER',
    status: 'ACTIVE',
    joinDate: '2024-01-10',
    yearsOfExperience: 8,
    vesselId: '2',
    vessel: mockVessels[1],
    certificates: [],
    trainings: [],
    rotations: [],
    notes: null,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
];

export const mockCrewCertificates = [
  {
    id: '1',
    crewMemberId: '1',
    crewMember: mockCrewMembers[0],
    certificateType: 'STCW_BASIC_SAFETY',
    certificateNumber: 'STCW-2023-001',
    issueDate: '2023-01-15',
    expiryDate: getDateString(60),
    issuingAuthority: 'Turkish Maritime Authority',
    issuingCountry: 'Turkey',
    warningThreshold: 30,
    isNotified30: true,
    isNotified60: false,
    isNotified90: false,
    notes: null,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: '2',
    crewMemberId: '1',
    crewMember: mockCrewMembers[0],
    certificateType: 'MEDICAL_CERTIFICATE',
    certificateNumber: 'MED-2023-001',
    issueDate: '2023-06-01',
    expiryDate: getDateString(365),
    issuingAuthority: 'Maritime Health Authority',
    issuingCountry: 'Turkey',
    warningThreshold: 30,
    isNotified30: false,
    isNotified60: false,
    isNotified90: false,
    notes: null,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: '3',
    crewMemberId: '2',
    crewMember: mockCrewMembers[1],
    certificateType: 'STCW_ADVANCED_FIRE',
    certificateNumber: 'STCW-2022-002',
    issueDate: '2022-12-01',
    expiryDate: getDateString(-10),
    issuingAuthority: 'IMO',
    issuingCountry: 'International',
    warningThreshold: 30,
    isNotified30: true,
    isNotified60: true,
    isNotified90: true,
    notes: null,
    createdAt: '2024-01-05T10:00:00Z',
    updatedAt: '2024-01-05T10:00:00Z',
  },
];

export const mockCrewTrainings = [
  {
    id: '1',
    crewMemberId: '1',
    crewMember: mockCrewMembers[0],
    trainingName: 'Advanced Fire Fighting',
    trainingType: 'FIRE_FIGHTING',
    status: 'COMPLETED',
    startDate: '2023-11-01',
    endDate: '2023-11-05',
    expiryDate: '2025-11-05',
    provider: 'Maritime Training Center',
    location: 'Istanbul',
    durationHours: 40,
    certificateNumber: 'TRN-2023-001',
    notes: null,
    createdAt: '2023-11-01T10:00:00Z',
    updatedAt: '2023-11-05T10:00:00Z',
  },
  {
    id: '2',
    crewMemberId: '2',
    crewMember: mockCrewMembers[1],
    trainingName: 'First Aid at Sea',
    trainingType: 'FIRST_AID',
    status: 'COMPLETED',
    startDate: '2023-09-15',
    endDate: '2023-09-17',
    expiryDate: '2025-09-17',
    provider: 'Maritime Safety Institute',
    location: 'Ankara',
    durationHours: 16,
    certificateNumber: 'TRN-2023-002',
    notes: null,
    createdAt: '2023-09-15T10:00:00Z',
    updatedAt: '2023-09-17T10:00:00Z',
  },
];

export const mockCrewRotations = [
  {
    id: '1',
    crewMemberId: '1',
    crewMember: mockCrewMembers[0],
    vesselId: '1',
    vessel: mockVessels[0],
    rotationType: 'JOINING',
    plannedDate: '2024-01-01',
    actualDate: '2024-01-01',
    port: 'Istanbul',
    reason: 'Normal rotation',
    notes: null,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: '2',
    crewMemberId: '2',
    crewMember: mockCrewMembers[1],
    vesselId: '1',
    vessel: mockVessels[0],
    rotationType: 'JOINING',
    plannedDate: '2024-01-05',
    actualDate: '2024-01-05',
    port: 'Izmir',
    reason: 'Normal rotation',
    notes: null,
    createdAt: '2024-01-05T10:00:00Z',
    updatedAt: '2024-01-05T10:00:00Z',
  },
  {
    id: '3',
    crewMemberId: '3',
    crewMember: mockCrewMembers[2],
    vesselId: '2',
    vessel: mockVessels[1],
    rotationType: 'JOINING',
    plannedDate: '2024-01-10',
    actualDate: '2024-01-10',
    port: 'Mersin',
    reason: 'Normal rotation',
    notes: null,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
];

export const mockInventoryItems = [
  {
    id: '1',
    name: 'Diesel Fuel',
    description: 'Marine diesel fuel',
    partNumber: 'FUEL-D-001',
    manufacturer: null,
    unit: 'LITER',
    quantity: 5000,
    minimumQuantity: 2000,
    maximumQuantity: 10000,
    unitPrice: 1.5,
    expiryDate: null,
    category: 'Fuel',
    vesselId: '1',
    vessel: mockVessels[0],
    locationId: null,
    location: null,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: '2',
    name: 'Engine Oil',
    description: 'Marine engine oil 15W-40',
    partNumber: 'OIL-E-001',
    manufacturer: 'Shell',
    unit: 'LITER',
    quantity: 50,
    minimumQuantity: 100,
    maximumQuantity: 500,
    unitPrice: 25.0,
    expiryDate: getDateString(180),
    category: 'Lubricants',
    vesselId: '1',
    vessel: mockVessels[0],
    locationId: null,
    location: null,
    createdAt: '2024-01-05T10:00:00Z',
    updatedAt: '2024-01-05T10:00:00Z',
  },
  {
    id: '3',
    name: 'Fire Extinguisher',
    description: 'Portable fire extinguisher 5kg',
    partNumber: 'FIRE-EXT-001',
    manufacturer: 'Safety First',
    unit: 'PIECE',
    quantity: 8,
    minimumQuantity: 10,
    maximumQuantity: 20,
    unitPrice: 150.0,
    expiryDate: getDateString(60),
    category: 'Safety Equipment',
    vesselId: '2',
    vessel: mockVessels[1],
    locationId: null,
    location: null,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
];

export const mockInventoryLocations = [
  {
    id: '1',
    name: 'Engine Room',
    description: 'Main engine room storage',
    vesselId: '1',
    vessel: mockVessels[0],
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: '2',
    name: 'Deck Store',
    description: 'Deck equipment storage',
    vesselId: '1',
    vessel: mockVessels[0],
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: '3',
    name: 'Galley',
    description: 'Kitchen storage',
    vesselId: '2',
    vessel: mockVessels[1],
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
];

export const mockInventoryTransactions = [
  {
    id: '1',
    itemId: '1',
    item: mockInventoryItems[0],
    transactionType: 'IN',
    quantity: 5000,
    unitPrice: 1.5,
    reference: 'PO-2024-001',
    notes: 'Initial stock',
    createdById: '1',
    createdBy: mockUsers[0],
    createdAt: '2024-01-01T10:00:00Z',
  },
  {
    id: '2',
    itemId: '2',
    item: mockInventoryItems[1],
    transactionType: 'OUT',
    quantity: 50,
    unitPrice: 25.0,
    reference: 'WO-2024-001',
    notes: 'Engine maintenance',
    createdById: '3',
    createdBy: mockUsers[2],
    createdAt: '2024-01-15T10:00:00Z',
  },
];

export const mockProcurementSuppliers = [
  {
    id: '1',
    name: 'Marine Supply Co.',
    contactPerson: 'John Smith',
    email: 'john@marinesupply.com',
    phone: '+1 555 123 4567',
    address: '123 Harbor Street',
    city: 'Istanbul',
    country: 'Turkey',
    taxNumber: 'TAX-001',
    website: 'www.marinesupply.com',
    notes: null,
    isActive: true,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: '2',
    name: 'Global Maritime Services',
    contactPerson: 'Maria Garcia',
    email: 'maria@globalmaritime.com',
    phone: '+1 555 234 5678',
    address: '456 Ocean Avenue',
    city: 'Ankara',
    country: 'Turkey',
    taxNumber: 'TAX-002',
    website: 'www.globalmaritime.com',
    notes: null,
    isActive: true,
    createdAt: '2024-01-05T10:00:00Z',
    updatedAt: '2024-01-05T10:00:00Z',
  },
];

export const mockProcurementRequests = [
  {
    id: '1',
    requestNumber: 'REQ-2024-0001',
    title: 'Engine Oil Request',
    description: 'Marine engine oil for maintenance',
    status: 'APPROVED',
    requiredDate: getDateString(30),
    estimatedCost: 5000,
    vesselId: '1',
    vessel: mockVessels[0],
    requestedById: '3',
    requestedBy: mockUsers[2],
    approvedById: '2',
    approvedBy: mockUsers[1],
    approvedAt: '2024-01-15T10:00:00Z',
    rejectionReason: null,
    orders: [],
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    requestNumber: 'REQ-2024-0002',
    title: 'Safety Equipment',
    description: 'Fire extinguishers and safety gear',
    status: 'PENDING_APPROVAL',
    requiredDate: getDateString(45),
    estimatedCost: 3000,
    vesselId: '2',
    vessel: mockVessels[1],
    requestedById: '3',
    requestedBy: mockUsers[2],
    approvedById: null,
    approvedBy: null,
    approvedAt: null,
    rejectionReason: null,
    orders: [],
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2024-01-20T10:00:00Z',
  },
];

export const mockProcurementOrders = [
  {
    id: '1',
    orderNumber: 'PO-2024-0001',
    requestId: '1',
    request: mockProcurementRequests[0],
    supplierId: '1',
    supplier: mockProcurementSuppliers[0],
    status: 'ORDERED',
    orderDate: getDateString(-5),
    expectedDeliveryDate: getDateString(25),
    actualDeliveryDate: null,
    totalAmount: 4800,
    currency: 'USD',
    terms: 'Net 30',
    createdById: '2',
    createdBy: mockUsers[1],
    approvedById: '2',
    approvedBy: mockUsers[1],
    quotes: [],
    createdAt: '2024-01-16T10:00:00Z',
    updatedAt: '2024-01-16T10:00:00Z',
  },
];

export const mockMaintenanceTasks = [
  {
    id: '1',
    title: 'Engine Oil Change',
    description: 'Regular engine oil change and filter replacement',
    vesselId: '1',
    vessel: mockVessels[0],
    scheduleId: null,
    schedule: null,
    status: 'PENDING',
    priority: 'MEDIUM',
    dueDate: getDateString(7),
    completedDate: null,
    equipment: 'Main Engine',
    location: 'Engine Room',
    assignedToId: null,
    assignedTo: null,
    estimatedHours: 4,
    workOrders: [],
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    title: 'Fire Extinguisher Inspection',
    description: 'Monthly fire extinguisher inspection and testing',
    vesselId: '1',
    vessel: mockVessels[0],
    scheduleId: null,
    schedule: null,
    status: 'OVERDUE',
    priority: 'HIGH',
    dueDate: getDateString(-5),
    completedDate: null,
    equipment: 'Fire Extinguishers',
    location: 'All Decks',
    assignedToId: null,
    assignedTo: null,
    estimatedHours: 2,
    workOrders: [],
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: '3',
    title: 'Generator Maintenance',
    description: 'Quarterly generator maintenance',
    vesselId: '2',
    vessel: mockVessels[1],
    scheduleId: null,
    schedule: null,
    status: 'COMPLETED',
    priority: 'HIGH',
    dueDate: getDateString(-10),
    completedDate: getDateString(-8),
    equipment: 'Auxiliary Generator',
    location: 'Engine Room',
    assignedToId: null,
    assignedTo: null,
    estimatedHours: 8,
    workOrders: [],
    createdAt: '2024-01-05T10:00:00Z',
    updatedAt: '2024-01-12T10:00:00Z',
  },
];

export const mockMaintenanceWorkOrders = [
  {
    id: '1',
    workOrderNumber: 'WO-2024-0001',
    taskId: '3',
    task: mockMaintenanceTasks[2],
    status: 'COMPLETED',
    startDate: getDateString(-10),
    completedDate: getDateString(-8),
    actualHours: 7,
    totalCost: 1500,
    notes: 'Maintenance completed successfully',
    createdById: '3',
    createdBy: mockUsers[2],
    assignedToId: '2',
    assignedTo: mockUsers[1],
    parts: [],
    createdAt: '2024-01-05T10:00:00Z',
    updatedAt: '2024-01-12T10:00:00Z',
  },
];

export const mockVoyages = [
  {
    id: '1',
    voyageNumber: 'VOY-2024-0001',
    vesselId: '1',
    vessel: mockVessels[0],
    status: 'IN_PROGRESS',
    startDate: getDateString(-10),
    endDate: null,
    originPort: 'Istanbul',
    destinationPort: 'Rotterdam',
    distance: 2500,
    fuelConsumed: 450,
    totalExpenses: 125000,
    portCalls: [],
    expenses: [],
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: '2',
    voyageNumber: 'VOY-2024-0002',
    vesselId: '2',
    vessel: mockVessels[1],
    status: 'COMPLETED',
    startDate: getDateString(-30),
    endDate: getDateString(-5),
    originPort: 'Mersin',
    destinationPort: 'Alexandria',
    distance: 800,
    fuelConsumed: 180,
    totalExpenses: 45000,
    portCalls: [],
    expenses: [],
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-25T10:00:00Z',
  },
];

export const mockIncidents = [
  {
    id: '1',
    vesselId: '1',
    vessel: mockVessels[0],
    incidentType: 'ACCIDENT',
    severity: 'HIGH',
    status: 'UNDER_INVESTIGATION',
    incidentDate: getDateString(-5),
    location: 'Engine Room',
    latitude: 36.8969,
    longitude: 30.7133,
    title: 'Engine Room Fire',
    description: 'Small fire detected in the engine room, immediately extinguished by crew. No injuries reported.',
    immediateActions: 'Fire suppression system activated, area evacuated, fire department notified',
    investigation: 'Investigation ongoing to determine root cause',
    rootCause: null,
    correctiveActions: null,
    preventiveActions: null,
    photos: null,
    reportedById: '3',
    reportedBy: mockUsers[2],
    investigatedById: null,
    investigatedBy: null,
    createdAt: getDateString(-5),
    updatedAt: getDateString(-5),
  },
  {
    id: '2',
    vesselId: '1',
    vessel: mockVessels[0],
    incidentType: 'NEAR_MISS',
    severity: 'MEDIUM',
    status: 'RESOLVED',
    incidentDate: getDateString(-15),
    location: 'Deck',
    latitude: 36.8969,
    longitude: 30.7133,
    title: 'Cargo Handling Near Miss',
    description: 'Cargo container nearly fell during loading operation. Safety procedures prevented accident.',
    immediateActions: 'Operation stopped, safety review conducted, additional safety measures implemented',
    investigation: 'Investigation completed',
    rootCause: 'Inadequate communication between crane operator and deck crew',
    correctiveActions: 'Enhanced communication protocols, additional training for deck crew',
    preventiveActions: 'Regular safety drills, improved signage, mandatory safety briefings before operations',
    photos: null,
    reportedById: '3',
    reportedBy: mockUsers[2],
    investigatedById: '2',
    investigatedBy: mockUsers[1],
    createdAt: getDateString(-15),
    updatedAt: getDateString(-10),
  },
  {
    id: '3',
    vesselId: '2',
    vessel: mockVessels[1],
    incidentType: 'NON_CONFORMITY',
    severity: 'LOW',
    status: 'CLOSED',
    incidentDate: getDateString(-30),
    location: 'Bridge',
    latitude: null,
    longitude: null,
    title: 'Navigation Equipment Non-Conformity',
    description: 'GPS system calibration found to be outside acceptable parameters during routine inspection.',
    immediateActions: 'GPS recalibrated, backup systems verified',
    investigation: 'Investigation completed',
    rootCause: 'Routine maintenance schedule not followed',
    correctiveActions: 'GPS recalibrated, maintenance schedule updated',
    preventiveActions: 'Automated maintenance reminders implemented, quarterly calibration checks scheduled',
    photos: null,
    reportedById: '2',
    reportedBy: mockUsers[1],
    investigatedById: '2',
    investigatedBy: mockUsers[1],
    createdAt: getDateString(-30),
    updatedAt: getDateString(-25),
  },
];

// Helper function to simulate API delay
export const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

